//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Исходное имя файла:
// Дата создания: 12.03.2016 18:58:04
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// В схеме отсутствуют комментарии для ApplicationData.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Инициализируйте новый объект ApplicationData.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Поскольку пространство имен, настроенное для этой ссылки на службу
        /// в Visual Studio, отличается от пространства имен, указанного
        /// в схеме сервера, для сопоставления этих пространств имен используйте преобразователи типов.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для RoomSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Room> RoomSet
        {
            get
            {
                if ((this._RoomSet == null))
                {
                    this._RoomSet = base.CreateQuery<Room>("RoomSet");
                }
                return this._RoomSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Room> _RoomSet;
        /// <summary>
        /// В схеме отсутствуют комментарии для ClientSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Client> ClientSet
        {
            get
            {
                if ((this._ClientSet == null))
                {
                    this._ClientSet = base.CreateQuery<Client>("ClientSet");
                }
                return this._ClientSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Client> _ClientSet;
        /// <summary>
        /// В схеме отсутствуют комментарии для SettlementSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Settlement> SettlementSet
        {
            get
            {
                if ((this._SettlementSet == null))
                {
                    this._SettlementSet = base.CreateQuery<Settlement>("SettlementSet");
                }
                return this._SettlementSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Settlement> _SettlementSet;
        /// <summary>
        /// В схеме отсутствуют комментарии для SexSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Sex> SexSet
        {
            get
            {
                if ((this._SexSet == null))
                {
                    this._SexSet = base.CreateQuery<Sex>("SexSet");
                }
                return this._SexSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Sex> _SexSet;
        /// <summary>
        /// В схеме отсутствуют комментарии для RoomTypeSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RoomType> RoomTypeSet
        {
            get
            {
                if ((this._RoomTypeSet == null))
                {
                    this._RoomTypeSet = base.CreateQuery<RoomType>("RoomTypeSet");
                }
                return this._RoomTypeSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RoomType> _RoomTypeSet;
        /// <summary>
        /// В схеме отсутствуют комментарии для RoomSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRoomSet(Room room)
        {
            base.AddObject("RoomSet", room);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для ClientSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClientSet(Client client)
        {
            base.AddObject("ClientSet", client);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для SettlementSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSettlementSet(Settlement settlement)
        {
            base.AddObject("SettlementSet", settlement);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для SexSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSexSet(Sex sex)
        {
            base.AddObject("SexSet", sex);
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для RoomTypeSet.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRoomTypeSet(RoomType roomType)
        {
            base.AddObject("RoomTypeSet", roomType);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Room\"><Key><PropertyRef Name=\"Id\" /></Key><Pro" +
                "perty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPatte" +
                "rn=\"Identity\" /><Property Name=\"NofBeds\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pr" +
                "operty Name=\"Cost\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"18\" Scale=\"2\" " +
                "/><Property Name=\"Room_RoomType\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property N" +
                "ame=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Typ" +
                "e=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength" +
                "=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"R" +
                "owVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation" +
                ":StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"RoomType\" Relation" +
                "ship=\"LightSwitchApplication.Room_RoomType\" ToRole=\"RoomType\" FromRole=\"Room\" />" +
                "<NavigationProperty Name=\"SettlementCollection\" Relationship=\"LightSwitchApplica" +
                "tion.Settlement_Room\" ToRole=\"Settlement\" FromRole=\"Room\" /></EntityType><Entity" +
                "Type Name=\"Client\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=" +
                "\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Prop" +
                "erty Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property " +
                "Name=\"S_Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Nam" +
                "e=\"Passport\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name" +
                "=\"Phone\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Ad" +
                "ress\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Birth" +
                "day\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Client_Sex\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" MaxLeng" +
                "th=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"" +
                "ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"" +
                "Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"fa" +
                "lse\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /><Navi" +
                "gationProperty Name=\"IdSex\" Relationship=\"LightSwitchApplication.Client_Sex\" ToR" +
                "ole=\"Sex\" FromRole=\"Client\" /><NavigationProperty Name=\"SettlementCollection\" Re" +
                "lationship=\"LightSwitchApplication.Settlement_Client\" ToRole=\"Settlement\" FromRo" +
                "le=\"Client\" /></EntityType><EntityType Name=\"Settlement\"><Key><PropertyRef Name=" +
                "\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:St" +
                "oreGeneratedPattern=\"Identity\" /><Property Name=\"Joined\" Type=\"Edm.DateTime\" Nul" +
                "lable=\"false\" /><Property Name=\"Eviction\" Type=\"Edm.DateTime\" Nullable=\"false\" /" +
                "><Property Name=\"Settlement_Client\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"Settlement_Room\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Cre" +
                "atedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.D" +
                "ateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /" +
                "><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersio" +
                "n\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGe" +
                "neratedPattern=\"Computed\" /><NavigationProperty Name=\"IdClient\" Relationship=\"Li" +
                "ghtSwitchApplication.Settlement_Client\" ToRole=\"Client\" FromRole=\"Settlement\" />" +
                "<NavigationProperty Name=\"IdRoom\" Relationship=\"LightSwitchApplication.Settlemen" +
                "t_Room\" ToRole=\"Room\" FromRole=\"Settlement\" /></EntityType><EntityType Name=\"Sex" +
                "\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"Name\" " +
                "Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"CreatedBy\" " +
                "Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeO" +
                "ffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Proper" +
                "ty Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=" +
                "\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedP" +
                "attern=\"Computed\" /><NavigationProperty Name=\"ClientCollection\" Relationship=\"Li" +
                "ghtSwitchApplication.Client_Sex\" ToRole=\"Client\" FromRole=\"Sex\" /></EntityType><" +
                "EntityType Name=\"RoomType\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"I" +
                "d\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\"" +
                " /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><P" +
                "roperty Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Cre" +
                "ated\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" " +
                "MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Propert" +
                "y Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" a" +
                "nnotation:StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"RoomColle" +
                "ction\" Relationship=\"LightSwitchApplication.Room_RoomType\" ToRole=\"Room\" FromRol" +
                "e=\"RoomType\" /></EntityType><Association Name=\"Client_Sex\"><End Role=\"Sex\" Type=" +
                "\"LightSwitchApplication.Sex\" Multiplicity=\"1\" /><End Role=\"Client\" Type=\"LightSw" +
                "itchApplication.Client\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Rol" +
                "e=\"Sex\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Client\"><PropertyR" +
                "ef Name=\"Client_Sex\" /></Dependent></ReferentialConstraint></Association><Associ" +
                "ation Name=\"Room_RoomType\"><End Role=\"RoomType\" Type=\"LightSwitchApplication.Roo" +
                "mType\" Multiplicity=\"1\" /><End Role=\"Room\" Type=\"LightSwitchApplication.Room\" Mu" +
                "ltiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"RoomType\"><PropertyRef " +
                "Name=\"Id\" /></Principal><Dependent Role=\"Room\"><PropertyRef Name=\"Room_RoomType\"" +
                " /></Dependent></ReferentialConstraint></Association><Association Name=\"Settleme" +
                "nt_Client\"><End Role=\"Client\" Type=\"LightSwitchApplication.Client\" Multiplicity=" +
                "\"1\" /><End Role=\"Settlement\" Type=\"LightSwitchApplication.Settlement\" Multiplici" +
                "ty=\"*\" /><ReferentialConstraint><Principal Role=\"Client\"><PropertyRef Name=\"Id\" " +
                "/></Principal><Dependent Role=\"Settlement\"><PropertyRef Name=\"Settlement_Client\"" +
                " /></Dependent></ReferentialConstraint></Association><Association Name=\"Settleme" +
                "nt_Room\"><End Role=\"Room\" Type=\"LightSwitchApplication.Room\" Multiplicity=\"1\" />" +
                "<End Role=\"Settlement\" Type=\"LightSwitchApplication.Settlement\" Multiplicity=\"*\"" +
                " /><ReferentialConstraint><Principal Role=\"Room\"><PropertyRef Name=\"Id\" /></Prin" +
                "cipal><Dependent Role=\"Settlement\"><PropertyRef Name=\"Settlement_Room\" /></Depen" +
                "dent></ReferentialConstraint></Association><EntityContainer Name=\"ApplicationDat" +
                "a\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"RoomSet\" EntityType=\"Light" +
                "SwitchApplication.Room\" /><EntitySet Name=\"ClientSet\" EntityType=\"LightSwitchApp" +
                "lication.Client\" /><EntitySet Name=\"SettlementSet\" EntityType=\"LightSwitchApplic" +
                "ation.Settlement\" /><EntitySet Name=\"SexSet\" EntityType=\"LightSwitchApplication." +
                "Sex\" /><EntitySet Name=\"RoomTypeSet\" EntityType=\"LightSwitchApplication.RoomType" +
                "\" /><AssociationSet Name=\"Client_Sex\" Association=\"LightSwitchApplication.Client" +
                "_Sex\"><End Role=\"Sex\" EntitySet=\"SexSet\" /><End Role=\"Client\" EntitySet=\"ClientS" +
                "et\" /></AssociationSet><AssociationSet Name=\"Room_RoomType\"";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @" Association=""LightSwitchApplication.Room_RoomType""><End Role=""RoomType"" EntitySet=""RoomTypeSet"" /><End Role=""Room"" EntitySet=""RoomSet"" /></AssociationSet><AssociationSet Name=""Settlement_Client"" Association=""LightSwitchApplication.Settlement_Client""><End Role=""Client"" EntitySet=""ClientSet"" /><End Role=""Settlement"" EntitySet=""SettlementSet"" /></AssociationSet><AssociationSet Name=""Settlement_Room"" Association=""LightSwitchApplication.Settlement_Room""><End Role=""Room"" EntitySet=""RoomSet"" /><End Role=""Settlement"" EntitySet=""SettlementSet"" /></AssociationSet><FunctionImport Name=""Query1"" ReturnType=""Collection(LightSwitchApplication.Client)"" EntitySet=""ClientSet"" m:HttpMethod=""GET""><Parameter Name=""SexId"" Type=""Edm.Int32"" Mode=""In"" /></FunctionImport><FunctionImport Name=""Query2"" ReturnType=""Collection(LightSwitchApplication.Settlement)"" EntitySet=""SettlementSet"" m:HttpMethod=""GET""><Parameter Name=""IdRoomType"" Type=""Edm.Int32"" Mode=""In"" /></FunctionImport><FunctionImport Name=""Microsoft_LightSwitch_GetCanInformation"" ReturnType=""Edm.String"" m:HttpMethod=""GET""><Parameter Name=""dataServiceMembers"" Type=""Edm.String"" Mode=""In"" /></FunctionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для LightSwitchApplication.Room.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RoomSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Room : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект Room.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="nofBeds">Начальное значение NofBeds.</param>
        /// <param name="cost">Начальное значение Cost.</param>
        /// <param name="room_RoomType">Начальное значение Room_RoomType.</param>
        /// <param name="rowVersion">Начальное значение RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Room CreateRoom(int ID, int nofBeds, decimal cost, int room_RoomType, byte[] rowVersion)
        {
            Room room = new Room();
            room.Id = ID;
            room.NofBeds = nofBeds;
            room.Cost = cost;
            room.Room_RoomType = room_RoomType;
            room.RowVersion = rowVersion;
            return room;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства NofBeds.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int NofBeds
        {
            get
            {
                return this._NofBeds;
            }
            set
            {
                this.OnNofBedsChanging(value);
                if (object.Equals(this.NofBeds, value))
                {
                    return;
                }
                this._NofBeds = value;
                this.OnNofBedsChanged();
                this.OnPropertyChanged("NofBeds");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _NofBeds;
        partial void OnNofBedsChanging(int value);
        partial void OnNofBedsChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Cost.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Cost
        {
            get
            {
                return this._Cost;
            }
            set
            {
                this.OnCostChanging(value);
                if (object.Equals(this.Cost, value))
                {
                    return;
                }
                this._Cost = value;
                this.OnCostChanged();
                this.OnPropertyChanged("Cost");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Cost;
        partial void OnCostChanging(decimal value);
        partial void OnCostChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Room_RoomType.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Room_RoomType
        {
            get
            {
                return this._Room_RoomType;
            }
            set
            {
                this.OnRoom_RoomTypeChanging(value);
                if (object.Equals(this.Room_RoomType, value))
                {
                    return;
                }
                this._Room_RoomType = value;
                this.OnRoom_RoomTypeChanged();
                this.OnPropertyChanged("Room_RoomType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Room_RoomType;
        partial void OnRoom_RoomTypeChanging(int value);
        partial void OnRoom_RoomTypeChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства CreatedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Created.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ModifiedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Modified.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства RowVersion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для RoomType.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RoomType RoomType
        {
            get
            {
                this.@__RoomType.EnsureValueInitialized();
                return this._RoomType;
            }
            set
            {
                RoomType previous = this.RoomType;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._RoomType = null;
                    this.@__RoomType.OnValueSet();
                    previous.RoomCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Room_RoomType = value.Id;
                    }
                    else
                    {
                        this.Room_RoomType = default(int);
                    }
                }
                this._RoomType = value;
                this.@__RoomType.OnValueSet();
                if ((value != null))
                {
                    value.@__RoomCollection.Add(this);
                }
                this.___OnPropertyChanged("RoomType");
                this.OnPropertyChanged("RoomType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RoomType _RoomType;
        /// <summary>
        /// В схеме отсутствуют комментарии для SettlementCollection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Settlement> SettlementCollection
        {
            get
            {
                this.@__SettlementCollection.EnsureValueInitialized();
                return this._SettlementCollection;
            }
            set
            {
                this._SettlementCollection = value;
                this.OnPropertyChanged("SettlementCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Settlement> _SettlementCollection = new global::System.Data.Services.Client.DataServiceCollection<Settlement>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для LightSwitchApplication.Client.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ClientSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Client : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект Client.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="name">Начальное значение Name.</param>
        /// <param name="s_Name">Начальное значение S_Name.</param>
        /// <param name="passport">Начальное значение Passport.</param>
        /// <param name="phone">Начальное значение Phone.</param>
        /// <param name="adress">Начальное значение Adress.</param>
        /// <param name="birthday">Начальное значение Birthday.</param>
        /// <param name="client_Sex">Начальное значение Client_Sex.</param>
        /// <param name="rowVersion">Начальное значение RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Client CreateClient(int ID, string name, string s_Name, string passport, string phone, string adress, global::System.DateTime birthday, int client_Sex, byte[] rowVersion)
        {
            Client client = new Client();
            client.Id = ID;
            client.Name = name;
            client.S_Name = s_Name;
            client.Passport = passport;
            client.Phone = phone;
            client.Adress = adress;
            client.Birthday = birthday;
            client.Client_Sex = client_Sex;
            client.RowVersion = rowVersion;
            return client;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства S_Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string S_Name
        {
            get
            {
                return this._S_Name;
            }
            set
            {
                this.OnS_NameChanging(value);
                if (object.Equals(this.S_Name, value))
                {
                    return;
                }
                this._S_Name = value;
                this.OnS_NameChanged();
                this.OnPropertyChanged("S_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _S_Name;
        partial void OnS_NameChanging(string value);
        partial void OnS_NameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Passport.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Passport
        {
            get
            {
                return this._Passport;
            }
            set
            {
                this.OnPassportChanging(value);
                if (object.Equals(this.Passport, value))
                {
                    return;
                }
                this._Passport = value;
                this.OnPassportChanged();
                this.OnPropertyChanged("Passport");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Passport;
        partial void OnPassportChanging(string value);
        partial void OnPassportChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Phone.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                if (object.Equals(this.Phone, value))
                {
                    return;
                }
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Adress.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Adress
        {
            get
            {
                return this._Adress;
            }
            set
            {
                this.OnAdressChanging(value);
                if (object.Equals(this.Adress, value))
                {
                    return;
                }
                this._Adress = value;
                this.OnAdressChanged();
                this.OnPropertyChanged("Adress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Adress;
        partial void OnAdressChanging(string value);
        partial void OnAdressChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Birthday.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Birthday
        {
            get
            {
                return this._Birthday;
            }
            set
            {
                this.OnBirthdayChanging(value);
                if (object.Equals(this.Birthday, value))
                {
                    return;
                }
                this._Birthday = value;
                this.OnBirthdayChanged();
                this.OnPropertyChanged("Birthday");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Birthday;
        partial void OnBirthdayChanging(global::System.DateTime value);
        partial void OnBirthdayChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Client_Sex.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Client_Sex
        {
            get
            {
                return this._Client_Sex;
            }
            set
            {
                this.OnClient_SexChanging(value);
                if (object.Equals(this.Client_Sex, value))
                {
                    return;
                }
                this._Client_Sex = value;
                this.OnClient_SexChanged();
                this.OnPropertyChanged("Client_Sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Client_Sex;
        partial void OnClient_SexChanging(int value);
        partial void OnClient_SexChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства CreatedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Created.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ModifiedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Modified.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства RowVersion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для IdSex.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Sex IdSex
        {
            get
            {
                this.@__IdSex.EnsureValueInitialized();
                return this._IdSex;
            }
            set
            {
                Sex previous = this.IdSex;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._IdSex = null;
                    this.@__IdSex.OnValueSet();
                    previous.ClientCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Client_Sex = value.Id;
                    }
                    else
                    {
                        this.Client_Sex = default(int);
                    }
                }
                this._IdSex = value;
                this.@__IdSex.OnValueSet();
                if ((value != null))
                {
                    value.@__ClientCollection.Add(this);
                }
                this.___OnPropertyChanged("IdSex");
                this.OnPropertyChanged("IdSex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Sex _IdSex;
        /// <summary>
        /// В схеме отсутствуют комментарии для SettlementCollection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Settlement> SettlementCollection
        {
            get
            {
                this.@__SettlementCollection.EnsureValueInitialized();
                return this._SettlementCollection;
            }
            set
            {
                this._SettlementCollection = value;
                this.OnPropertyChanged("SettlementCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Settlement> _SettlementCollection = new global::System.Data.Services.Client.DataServiceCollection<Settlement>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для LightSwitchApplication.Settlement.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SettlementSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Settlement : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект Settlement.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="joined">Начальное значение Joined.</param>
        /// <param name="eviction">Начальное значение Eviction.</param>
        /// <param name="settlement_Client">Начальное значение Settlement_Client.</param>
        /// <param name="settlement_Room">Начальное значение Settlement_Room.</param>
        /// <param name="rowVersion">Начальное значение RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Settlement CreateSettlement(int ID, global::System.DateTime joined, global::System.DateTime eviction, int settlement_Client, int settlement_Room, byte[] rowVersion)
        {
            Settlement settlement = new Settlement();
            settlement.Id = ID;
            settlement.Joined = joined;
            settlement.Eviction = eviction;
            settlement.Settlement_Client = settlement_Client;
            settlement.Settlement_Room = settlement_Room;
            settlement.RowVersion = rowVersion;
            return settlement;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Joined.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Joined
        {
            get
            {
                return this._Joined;
            }
            set
            {
                this.OnJoinedChanging(value);
                if (object.Equals(this.Joined, value))
                {
                    return;
                }
                this._Joined = value;
                this.OnJoinedChanged();
                this.OnPropertyChanged("Joined");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Joined;
        partial void OnJoinedChanging(global::System.DateTime value);
        partial void OnJoinedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Eviction.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Eviction
        {
            get
            {
                return this._Eviction;
            }
            set
            {
                this.OnEvictionChanging(value);
                if (object.Equals(this.Eviction, value))
                {
                    return;
                }
                this._Eviction = value;
                this.OnEvictionChanged();
                this.OnPropertyChanged("Eviction");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Eviction;
        partial void OnEvictionChanging(global::System.DateTime value);
        partial void OnEvictionChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Settlement_Client.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Settlement_Client
        {
            get
            {
                return this._Settlement_Client;
            }
            set
            {
                this.OnSettlement_ClientChanging(value);
                if (object.Equals(this.Settlement_Client, value))
                {
                    return;
                }
                this._Settlement_Client = value;
                this.OnSettlement_ClientChanged();
                this.OnPropertyChanged("Settlement_Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Settlement_Client;
        partial void OnSettlement_ClientChanging(int value);
        partial void OnSettlement_ClientChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Settlement_Room.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Settlement_Room
        {
            get
            {
                return this._Settlement_Room;
            }
            set
            {
                this.OnSettlement_RoomChanging(value);
                if (object.Equals(this.Settlement_Room, value))
                {
                    return;
                }
                this._Settlement_Room = value;
                this.OnSettlement_RoomChanged();
                this.OnPropertyChanged("Settlement_Room");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Settlement_Room;
        partial void OnSettlement_RoomChanging(int value);
        partial void OnSettlement_RoomChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства CreatedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Created.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ModifiedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Modified.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства RowVersion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для IdClient.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Client IdClient
        {
            get
            {
                this.@__IdClient.EnsureValueInitialized();
                return this._IdClient;
            }
            set
            {
                Client previous = this.IdClient;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._IdClient = null;
                    this.@__IdClient.OnValueSet();
                    previous.SettlementCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Settlement_Client = value.Id;
                    }
                    else
                    {
                        this.Settlement_Client = default(int);
                    }
                }
                this._IdClient = value;
                this.@__IdClient.OnValueSet();
                if ((value != null))
                {
                    value.@__SettlementCollection.Add(this);
                }
                this.___OnPropertyChanged("IdClient");
                this.OnPropertyChanged("IdClient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Client _IdClient;
        /// <summary>
        /// В схеме отсутствуют комментарии для IdRoom.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Room IdRoom
        {
            get
            {
                this.@__IdRoom.EnsureValueInitialized();
                return this._IdRoom;
            }
            set
            {
                Room previous = this.IdRoom;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._IdRoom = null;
                    this.@__IdRoom.OnValueSet();
                    previous.SettlementCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Settlement_Room = value.Id;
                    }
                    else
                    {
                        this.Settlement_Room = default(int);
                    }
                }
                this._IdRoom = value;
                this.@__IdRoom.OnValueSet();
                if ((value != null))
                {
                    value.@__SettlementCollection.Add(this);
                }
                this.___OnPropertyChanged("IdRoom");
                this.OnPropertyChanged("IdRoom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Room _IdRoom;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для LightSwitchApplication.Sex.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SexSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Sex : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект Sex.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="name">Начальное значение Name.</param>
        /// <param name="rowVersion">Начальное значение RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Sex CreateSex(int ID, string name, byte[] rowVersion)
        {
            Sex sex = new Sex();
            sex.Id = ID;
            sex.Name = name;
            sex.RowVersion = rowVersion;
            return sex;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства CreatedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Created.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ModifiedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Modified.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства RowVersion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для ClientCollection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Client> ClientCollection
        {
            get
            {
                this.@__ClientCollection.EnsureValueInitialized();
                return this._ClientCollection;
            }
            set
            {
                this._ClientCollection = value;
                this.OnPropertyChanged("ClientCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Client> _ClientCollection = new global::System.Data.Services.Client.DataServiceCollection<Client>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// В схеме отсутствуют комментарии для LightSwitchApplication.RoomType.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RoomTypeSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RoomType : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Создайте новый объект RoomType.
        /// </summary>
        /// <param name="ID">Начальное значение Id.</param>
        /// <param name="name">Начальное значение Name.</param>
        /// <param name="rowVersion">Начальное значение RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RoomType CreateRoomType(int ID, string name, byte[] rowVersion)
        {
            RoomType roomType = new RoomType();
            roomType.Id = ID;
            roomType.Name = name;
            roomType.RowVersion = rowVersion;
            return roomType;
        }
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства CreatedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Created.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства ModifiedBy.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства Modified.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для свойства RowVersion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// В схеме отсутствуют комментарии для RoomCollection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Room> RoomCollection
        {
            get
            {
                this.@__RoomCollection.EnsureValueInitialized();
                return this._RoomCollection;
            }
            set
            {
                this._RoomCollection = value;
                this.OnPropertyChanged("RoomCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Room> _RoomCollection = new global::System.Data.Services.Client.DataServiceCollection<Room>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
