//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Client
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Client :
        global::LightSwitchApplication.Client.DetailsClass.IImplementation
    {
        partial void OnClient_SexChanged()
        {
            this.___OnPropertyChanged("Client_Sex");
            this.___OnPropertyChanged("IdSex");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnS_NameChanged()
        {
            this.___OnPropertyChanged("S_Name");
        }
        
        partial void OnPassportChanged()
        {
            this.___OnPropertyChanged("Passport");
        }
        
        partial void OnPhoneChanged()
        {
            this.___OnPropertyChanged("Phone");
        }
        
        partial void OnAdressChanged()
        {
            this.___OnPropertyChanged("Adress");
        }
        
        partial void OnBirthdayChanged()
        {
            this.___OnPropertyChanged("Birthday");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Client.DetailsClass.IImplementation.IdSex
        {
            get
            {
                return this.IdSex;
            }
            set
            {
                this.IdSex = (global::LightSwitchApplication.Implementation.Sex)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Sex> __IdSex
        {
            get
            {
                if (this.___IdSex == null)
                {
                    this.___IdSex = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Sex>(
                        this,
                        "IdSex",
                        new string[] { "Client_Sex" },
                        e => global::System.Object.Equals(e.Id, this.Client_Sex),
                        () => this._IdSex,
                        e => this._IdSex = e);
                }
                return this.___IdSex;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Sex> ___IdSex;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.SettlementCollection
        {
            get
            {
                return this.SettlementCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Settlement> __SettlementCollection
        {
            get
            {
                if (this.___SettlementCollection == null)
                {
                    this.___SettlementCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Settlement>(
                        this,
                        "SettlementCollection",
                        () => this._SettlementCollection,
                        e => global::System.Object.Equals(e.Settlement_Client, this.Id));
                }
                return this.___SettlementCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Settlement> ___SettlementCollection;
        
    }
    #endregion
    
    #region Room
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Room :
        global::LightSwitchApplication.Room.DetailsClass.IImplementation
    {
        partial void OnRoom_RoomTypeChanged()
        {
            this.___OnPropertyChanged("Room_RoomType");
            this.___OnPropertyChanged("RoomType");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNofBedsChanged()
        {
            this.___OnPropertyChanged("NofBeds");
        }
        
        partial void OnCostChanged()
        {
            this.___OnPropertyChanged("Cost");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Room.DetailsClass.IImplementation.RoomType
        {
            get
            {
                return this.RoomType;
            }
            set
            {
                this.RoomType = (global::LightSwitchApplication.Implementation.RoomType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RoomType> __RoomType
        {
            get
            {
                if (this.___RoomType == null)
                {
                    this.___RoomType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RoomType>(
                        this,
                        "RoomType",
                        new string[] { "Room_RoomType" },
                        e => global::System.Object.Equals(e.Id, this.Room_RoomType),
                        () => this._RoomType,
                        e => this._RoomType = e);
                }
                return this.___RoomType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RoomType> ___RoomType;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Room.DetailsClass.IImplementation.SettlementCollection
        {
            get
            {
                return this.SettlementCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Settlement> __SettlementCollection
        {
            get
            {
                if (this.___SettlementCollection == null)
                {
                    this.___SettlementCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Settlement>(
                        this,
                        "SettlementCollection",
                        () => this._SettlementCollection,
                        e => global::System.Object.Equals(e.Settlement_Room, this.Id));
                }
                return this.___SettlementCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Settlement> ___SettlementCollection;
        
    }
    #endregion
    
    #region RoomType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RoomType :
        global::LightSwitchApplication.RoomType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RoomType.DetailsClass.IImplementation.RoomCollection
        {
            get
            {
                return this.RoomCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Room> __RoomCollection
        {
            get
            {
                if (this.___RoomCollection == null)
                {
                    this.___RoomCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Room>(
                        this,
                        "RoomCollection",
                        () => this._RoomCollection,
                        e => global::System.Object.Equals(e.Room_RoomType, this.Id));
                }
                return this.___RoomCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Room> ___RoomCollection;
        
    }
    #endregion
    
    #region Settlement
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Settlement :
        global::LightSwitchApplication.Settlement.DetailsClass.IImplementation
    {
        partial void OnSettlement_ClientChanged()
        {
            this.___OnPropertyChanged("Settlement_Client");
            this.___OnPropertyChanged("IdClient");
        }
        
        partial void OnSettlement_RoomChanged()
        {
            this.___OnPropertyChanged("Settlement_Room");
            this.___OnPropertyChanged("IdRoom");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnJoinedChanged()
        {
            this.___OnPropertyChanged("Joined");
        }
        
        partial void OnEvictionChanged()
        {
            this.___OnPropertyChanged("Eviction");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Settlement.DetailsClass.IImplementation.IdClient
        {
            get
            {
                return this.IdClient;
            }
            set
            {
                this.IdClient = (global::LightSwitchApplication.Implementation.Client)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> __IdClient
        {
            get
            {
                if (this.___IdClient == null)
                {
                    this.___IdClient = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "IdClient",
                        new string[] { "Settlement_Client" },
                        e => global::System.Object.Equals(e.Id, this.Settlement_Client),
                        () => this._IdClient,
                        e => this._IdClient = e);
                }
                return this.___IdClient;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> ___IdClient;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Settlement.DetailsClass.IImplementation.IdRoom
        {
            get
            {
                return this.IdRoom;
            }
            set
            {
                this.IdRoom = (global::LightSwitchApplication.Implementation.Room)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Room> __IdRoom
        {
            get
            {
                if (this.___IdRoom == null)
                {
                    this.___IdRoom = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Room>(
                        this,
                        "IdRoom",
                        new string[] { "Settlement_Room" },
                        e => global::System.Object.Equals(e.Id, this.Settlement_Room),
                        () => this._IdRoom,
                        e => this._IdRoom = e);
                }
                return this.___IdRoom;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Room> ___IdRoom;
        
    }
    #endregion
    
    #region Sex
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Sex :
        global::LightSwitchApplication.Sex.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Sex.DetailsClass.IImplementation.ClientCollection
        {
            get
            {
                return this.ClientCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Client> __ClientCollection
        {
            get
            {
                if (this.___ClientCollection == null)
                {
                    this.___ClientCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "ClientCollection",
                        () => this._ClientCollection,
                        e => global::System.Object.Equals(e.Client_Sex, this.Id));
                }
                return this.___ClientCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Client> ___ClientCollection;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Room))
            {
                return new global::LightSwitchApplication.Implementation.Room();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RoomType))
            {
                return new global::LightSwitchApplication.Implementation.RoomType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Settlement))
            {
                return new global::LightSwitchApplication.Implementation.Settlement();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Sex))
            {
                return new global::LightSwitchApplication.Implementation.Sex();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Client) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Client);
            }
            if (typeof(global::LightSwitchApplication.Room) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Room);
            }
            if (typeof(global::LightSwitchApplication.RoomType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RoomType);
            }
            if (typeof(global::LightSwitchApplication.Settlement) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Settlement);
            }
            if (typeof(global::LightSwitchApplication.Sex) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Sex);
            }
            return null;
        }
    }
}
