//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Позволяет управлять безопасностью приложения.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// AllAccess
        /// </summary>
        public const string AllAccess = "LightSwitchApplication:AllAccess";
        /// <summary>
        /// EmployeeAccess
        /// </summary>
        public const string EmployeeAccess = "LightSwitchApplication:EmployeeAccess";
        /// <summary>
        /// GuestAccess
        /// </summary>
        public const string GuestAccess = "LightSwitchApplication:GuestAccess";

        /// <summary>
        /// Получение всех разрешений, определенных для приложения.  К ним также относятся системные и определяемые пользователем разрешения.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
